name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository code
      - uses: actions/checkout@v2

      # Setup Node.js version 20
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Install dependencies and build your project
      - name: Install and build
        run: |
          npm ci
          npm run build

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0.7.1
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_CHAT_APP_2023_UNIQUE }}'
          channelId: live
          projectId: my-chat-app-2023-unique
